source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'
use_frameworks!

target 'JustPromises_Example' do
  pod 'JustPromises', :path => '../'

  target 'JustPromises_Tests' do
    inherit! :search_paths

    
  end
end
